# -*- coding: utf-8 -*-
"""
Created on Tue Mar 15 16:16:57 2016

@author: wxt
"""

"""
Problem 45:

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""
# When n is odd, the triangle number is a hexagonal number

import math

def isPentagonal(num):
    
    check = (1 + math.sqrt(1 + 24*num)) / 6
    
    return int(check) == check

def findnum(start = 287):
    
    n = start
    while True:
        num = n * (n+1) / 2
        if isPentagonal(num):
            return n, num
        n += 2

if __name__ == '__main__':
    
    print findnum() # ~23.3ms